name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish App
    runs-on: windows-2025

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install NPM dependencies
        run: npm ci

      #      - name: Run ESLint
      #        run: npm run lint

      - name: Publish Electron App
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
