name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  #  lint:
  #    name: Lint Code
  #    runs-on: ubuntu-latest
  #
  #    steps:
  #      - name: Checkout repository
  #        uses: actions/checkout@v4
  #
  #      - name: Setup Node.js
  #        uses: actions/setup-node@v4
  #        with:
  #          node-version: "20"
  #          cache: "npm"
  #
  #      - name: Install NPM dependencies
  #        run: npm ci
  #
  #      - name: Run ESLint
  #        run: npm run lint
  #
  publish:
    name: Publish App
    runs-on: ubuntu-latest
    #    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install NPM dependencies
        run: npm ci

      - name: Install mono
        run: sudo apt install ca-certificates gnupg &&
          sudo gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF &&
          echo "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list &&
          sudo apt update &&
          sudo apt install mono-devel

      - name: Install wine
        run: sudo dpkg --add-architecture i386 &&
          sudo mkdir -pm755 /etc/apt/keyrings &&
          wget -O - https://dl.winehq.org/wine-builds/winehq.key | sudo gpg --dearmor -o /etc/apt/keyrings/winehq-archive.key - &&
          sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/noble/winehq-noble.sources &&
          sudo apt update &&
          sudo apt install --install-recommends winehq-devel

      - name: Publish Electron App
        run: npm run publish -- --arch x64 --platform win32
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
